__authors__ = ["matthewaclarke", "charliegeorgebarker", "yuxinsun"]


import json
import pickle
from os.path import isfile
from pathlib import Path
from typing import Any

from pandas import ExcelWriter


# save to pickle files
def save_pickle(file_path: str, to_save: Any):
    if file_path[-4:] != ".pkl":
        file_path += ".pkl"
    with open(file_path, "wb") as f:
        pickle.dump(to_save, f, protocol=2)  # pickle.HIGHEST_PROTOCOL


# read from pickle files
def read_pickle(file_path):
    if file_path[-4:] != ".pkl":
        file_path += ".pkl"

    with open(file_path, "rb") as f:
        data = pickle.load(f, encoding="latin-1")

    return data


# save pd.Dataframe to excel
def save_excel(file_path, df, sheet_name="Sheet1", index=False):
    # if not isdir(path):
    #     raise ValueError('invalid path: %s' % path)

    if file_path[-5:] != ".xlsx":
        file_path += ".xlsx"

    if not isfile(file_path):
        df.to_excel(file_path, sheet_name=sheet_name, index=index)
    else:
        with ExcelWriter(file_path, mode="a", if_sheet_exists="replace") as writer:
            df.to_excel(writer, sheet_name=sheet_name, index=index)


def read_json(file_path: str | Path) -> dict:
    """
    Read .json file

    :param path: str, file directory
    :param file_name: str, file name

    :return: dict from .json file

    """
    if file_path is None:
        raise ValueError("file_path is None")

    if isinstance(file_path, str):
        file_path = Path(file_path)

    if file_path.suffix != ".json":
        file_path = file_path.with_suffix(".json")

    f = open(file_path)
    data = json.load(f)

    return data


def save_json(file_path, to_save):
    """
    Save .json file

    :param path: str, output directory
    :param file_name: str, file name
    :param to_save: model to be saved, generated by function _gen_json(.) below

    """

    if not isinstance(to_save, dict):
        raise ValueError("to_save must be a dictionary")

    if file_path[-5:] != ".json":
        file_path += ".json"

    f = open(file_path, "w")
    json.dump(to_save, f, indent=4)
